name: tbib_upgrade_app
description: This package for check app update version by upgrader.
version: 1.0.6
homepage: "https://github.com/the-best-is-best/tbib_upgrade_app"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.2
  upgrader: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
